pipeline {
   agent any
   
   environment {
       DEMO='1.3'
       MODE='production'
   }

   stages {
      stage('Build') {
         steps {
            echo "This is build mode is $MODE of demo $DEMO"
            
         }
      }
      stage('Test') {
         environment {
             MODE='development'
         }
         steps {
            echo "This is Test, mode is $MODE of demo $DEMO"
            
         }
      }
      stage('Deploy') {
         steps {
            echo "This is Deploy mode is $MODE of demo $DEMO"
            
         }
      }
   }
}
