pipeline {
   agent any
   
   environment {
       DEMO='1.3'
   }

   stages {
      stage('Build') {
         steps {
            echo "This is build number $BUILD_NUMBER of demo $DEMO"
            
         }
      }
      stage('Test') {
         steps {
            echo "This is Test number $BUILD_NUMBER of demo $DEMO"
            
         }
      }
      stage('Deploy') {
         steps {
            echo "This is Deploy number $BUILD_NUMBER of demo $DEMO"
            
         }
      }
   }
}
